"""LLM structured output schemas for session features."""

from pydantic import BaseModel, Field


class SessionTitleSchema(BaseModel):
    """3-4 word session title generated by the LLM."""
    title: str = Field(..., min_length=1, max_length=255)
