"""add user_auth_providers

Revision ID: b151df38dc72
Revises: dce74a517399
Create Date: 2026-05-04 12:46:29.411957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b151df38dc72'
down_revision: Union[str, None] = 'dce74a517399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user_id')
    )
    op.create_index('idx_auth_providers_user', 'user_auth_providers', ['user_id'], unique=False)

    # Migrate existing password hashes from users table to user_auth_providers
    op.execute("""
        INSERT INTO user_auth_providers (id, user_id, provider, email, password_hash, is_primary)
        SELECT gen_random_uuid(), id, 'email', email, password_hash, true
        FROM users
        WHERE password_hash IS NOT NULL
    """)

    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # Restore password hashes from user_auth_providers back to users
    op.execute("""
        UPDATE users
        SET password_hash = uap.password_hash
        FROM user_auth_providers uap
        WHERE uap.user_id = users.id AND uap.provider = 'email' AND uap.password_hash IS NOT NULL
    """)

    op.drop_index('idx_auth_providers_user', table_name='user_auth_providers')
    op.drop_table('user_auth_providers')
    # ### end Alembic commands ###
