"""add indexes to sessions table

Revision ID: a796cea3d652
Revises: 08b4b879dc4c
Create Date: 2026-05-08 08:41:38.496496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a796cea3d652'
down_revision: Union[str, None] = '08b4b879dc4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_sessions_user_created', 'sessions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('idx_sessions_user_created', table_name='sessions')
    # ### end Alembic commands ###
