"""add last transcript id to sessions table

Revision ID: 0ce7fd5161ee
Revises: 458cf688a1c7
Create Date: 2026-04-28 23:08:12.248628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce7fd5161ee'
down_revision: Union[str, None] = '458cf688a1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_summarized_transcript_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'session_timeline', ['last_summarized_transcript_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'last_summarized_transcript_id')
    # ### end Alembic commands ###
