"""remove dob from user registration

Revision ID: da3767f9355b
Revises: b151df38dc72
Create Date: 2026-05-04 14:16:06.517855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3767f9355b'
down_revision: Union[str, None] = 'b151df38dc72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dob')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
